### ISSUE TITLE
Why the prediction is binary?

### ISSUE THREAD

**Issue by skydome20** [while/FTRLProximal#8]
It's awesome to find such online learning algorithms package on R-Cran.
I try to analyze data from Kaggle for practice, and the returning prediction is either 0 or 1.
Even I set `predict(, type='response')`,  the prediction is fixed as 0/1.
If I remember it correctly, the core of FTRL-Proximal is still logistic regression for application on CTR.
I notice one possible cause may be that when training the ftrl model by using `ftrlprox()` function, it requires the dependent variable should be **factor type**. 
Is it possible to get the prediction being probabilities (0~1, like logistic regression) rather than binary type?

**Comment by while** [comment]
The prediction should be probabilities. I haven't added support for class response yet. 

Check this example: 

    library(FTRLProximal)
    library(mlbench)
    
    set.seed(1)
    dat <- as.data.frame(mlbench.2dnormals(10000,2))
    X <- model.matrix(classes ~ ., dat)
    mdl <- ftrlprox(X, dat$classes, lambda=0, alpha=1, a=0.3)
    
    print(mdl)
    # Coefficients:                       
    # (Intercept) -0.00241861
    # x.1         -2.13835295
    # x.2         -1.99080792
    
    testdat <- as.data.frame(mlbench.2dnormals(10,2))
    testX <- model.matrix(classes ~ ., testdat)
    
    predict(mdl, testX)
    # [1] 9.24072e-01 9.64140e-01 1.82251e-03 1.04256e-02 6.01930e-01 3.01652e-05 4.73957e-04 8.38403e-03 9.81564e-01 9.99353e-01
